### ISSUE TITLE
Class date-filter missing

### ISSUE THREAD

**Issue by angelocala94** [64robots/nova-date-filter#11]
If I have more filters in my resource, only the first filter has the class "date-filter", all the following ones do not have this class and they have ui problems.

Nova Version: 1.1.7

<img src="https://user-images.githubusercontent.com/6445721/48982885-7329d380-f0e8-11e8-9b22-c90193b53b21.png" width="400px" />

**Comment by disitec** [comment]
Fixed in 0.3.2 🎉
